apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-exercise-deployment
  labels:
    app: k8-exercise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-exercise
  template:
    metadata:
      labels:
        app: k8-exercise
    spec:
      containers:
      - name: k8-exercise
        image: davidrthorn/kube-exercise-server:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"